name: ntfy_flutter
description: A Flutter port of the ntfy Android app.
publish_to: none
version: 0.1.16+17

environment:
  sdk: ^3.13.0

dependencies:
  dynamic_color: ^1.9.0
  file_picker: ^12.0.0
  flutter:
    sdk: flutter
  flutter_linkify: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown_plus: ^1.0.12
  flutter_secure_storage: ^11.0.0
  open_filex: ^4.7.0
  package_info_plus: ^10.2.1
  path_provider: ^2.1.6
  share_plus: ^13.3.0
  shared_preferences: ^2.5.5
  sqflite: ^2.4.3
  url_launcher: ^6.3.2
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.4.2+1

flutter:
  uses-material-design: true
  assets:
    - assets/emoji.json
    - assets/i18n.json
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
    - family: HankenGrotesk
      fonts:
        - asset: assets/fonts/HankenGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/HankenGrotesk-Bold.ttf
          weight: 700
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrainsMono-SemiBold.ttf
          weight: 600
    - family: GoldenRoboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
